package com.example.VoloMap.server

import com.fasterxml.jackson.annotation.JsonIgnore
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import java.time.Instant
import java.time.LocalDateTime

@Entity
@Table(name = "volunteer_activities")
class VolunteerActivity constructor(
    // Primary key — value is auto-generated by the database on insert
    // Default value of 0 means "not yet persisted"
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long = 0,

    // Name of the volunteer opportunity — required field
    var name: String,

    // Optional fields — nullable because the data source may not provide them
    @Column(columnDefinition = "TEXT") //Column has no size limit
    var description: String? = null,
    @Column(columnDefinition = "TEXT")
    var addressText: String? = null,

    // URL of the original listing, used for deduplication and linking back to source
    @Column(columnDefinition = "TEXT")
    var sourceUrl: String? = null,

    var category: String? = null,

    // Coordinates are nullable until geocoding is implemented
    var latitude: Double? = null,
    var longitude: Double? = null,

    // Whether this entry is shown to users — allows hiding without deleting
    var isActive: Boolean = true,

    // Timestamp of when this record was inserted into our database
    var createdAt: Instant = Instant.now(),

    var dateTime: LocalDateTime = LocalDateTime.now(),

    // Anbieter, der diese Aktivität angelegt hat — null für bestehende gescrapte/geseedete Einträge.
    // @JsonIgnore verhindert, dass das verschachtelte User-Objekt (inkl. Passwort-Hash) über die
    // API ausgeliefert wird.
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "created_by")
    var createdBy: User? = null,
)