export const ACTIVITY_CATEGORIES = [
    "Bildung",
    "Familie & Nachbarschaft",
    "Flüchtlingshilfe",
    "Hausaufgabenbetreuung",
    "Kultur",
    "Leben im Alter",
    "LGBTQ",
    "Obdachlosigkeit",
    "Patenschaften",
    "Soziales",
    "Sport und Bewegung",
    "Tierhilfe",
    "Übersetzen / Dolmetschen",
    "Umwelt, Natur und Tierschutz",
    "Vereinsarbeit",
    "Verkauf",
    "Sonstiges",
];
